export const qualityOptions = [
  { label: "Quality: All", value: "all" },
  { label: "480p", value: "480p" },
  { label: "720p", value: "720p" },
  { label: "1080p", value: "1080p" },
  { label: "1080p.x265", value: "1080p.x265" },
  { label: "2160p", value: "2160p" },
  { label: "3D", value: "3D" },
];

export const genreOptions = [
  { label: "Genre: All", value: "all" },
  { label: "Action", value: "action" },
  { label: "Adventure", value: "adventure" },
  { label: "Animation", value: "animation" },
  { label: "Biography", value: "biography" },
  { label: "Comedy", value: "comedy" },
  { label: "Crime", value: "crime" },
  { label: "Documentary", value: "documentary" },
  { label: "Drama", value: "drama" },
  { label: "Family", value: "family" },
  { label: "Fantasy", value: "fantasy" },
  { label: "Film-Noir", value: "film-noir" },
  { label: "Game-Show", value: "game-show" },
  { label: "History", value: "history" },
  { label: "Horror", value: "horror" },
  { label: "Music", value: "music" },
  { label: "Musical", value: "musical" },
  { label: "Mystery", value: "mystery" },
  { label: "News", value: "news" },
  { label: "Reality-TV", value: "reality-tv" },
  { label: "Romance", value: "romance" },
  { label: "Sci-Fi", value: "sci-fi" },
  { label: "Sport", value: "sport" },
  { label: "Talk-Show", value: "talk-show" },
  { label: "Thriller", value: "thriller" },
  { label: "War", value: "war" },
  { label: "Western", value: "western" },
];

export const ratingOptions = [
  { label: "Rating: All", value: "0" },
  { label: "9+", value: "9" },
  { label: "8+", value: "8" },
  { label: "7+", value: "7" },
  { label: "6+", value: "6" },
  { label: "5+", value: "5" },
  { label: "4+", value: "4" },
  { label: "3+", value: "3" },
  { label: "2+", value: "2" },
  { label: "1+", value: "1" },
];

export const yearOptions = [
  { label: "Year: All", value: "0" },
  { label: "2026", value: "2026" },
  { label: "2025", value: "2025" },
  { label: "2020-now", value: "2020-2026" },
  { label: "2010-now", value: "2010-2026" },
  { label: "2010-2019", value: "2010-2019" },
  { label: "2000-2009", value: "2000-2009" },
  { label: "1990-1999", value: "1990-1999" },
  { label: "1980-1989", value: "1980-1989" },
  { label: "1970-1979", value: "1970-1979" },
  { label: "1950-1969", value: "1950-1969" },
  { label: "1900-1949", value: "1900-1949" },
];

export const languageOptions = [
  { label: "Language: All", value: "all" },
  { label: "English", value: "en" },
  { label: "Foreign", value: "foreign" },
  { label: "French (3520)", value: "fr" },
  { label: "Japanese (2914)", value: "ja" },
  { label: "Spanish (1982)", value: "es" },
  { label: "Italian (1623)", value: "it" },
  { label: "German (1346)", value: "de" },
  { label: "Chinese (1167)", value: "zh" },
  { label: "Korean (1001)", value: "ko" },
  { label: "Hindi (922)", value: "hi" },
  { label: "Cantonese (870)", value: "cn" },
  { label: "Turkish (503)", value: "tr" },
  { label: "Portuguese (494)", value: "pt" },
  { label: "Swedish (476)", value: "sv" },
  { label: "Romanian (471)", value: "ro" },
  { label: "Russian (435)", value: "ru" },
  { label: "Polish (403)", value: "pl" },
  { label: "Dutch (366)", value: "nl" },
  { label: "Thai (271)", value: "th" },
  { label: "Danish (269)", value: "da" },
  { label: "Indonesian (242)", value: "id" },
  { label: "Tamil (234)", value: "ta" },
  { label: "Telugu (227)", value: "te" },
  { label: "Norwegian (203)", value: "no" },
  { label: "Arabic (193)", value: "ar" },
  { label: "Tagalog (171)", value: "tl" },
  { label: "Finnish (166)", value: "fi" },
  { label: "Czech (162)", value: "cs" },
  { label: "Hungarian (158)", value: "hu" },
  { label: "Vietnamese (138)", value: "vi" },
  { label: "Persian (117)", value: "fa" },
  { label: "Malayalam (103)", value: "ml" },
  { label: "Hebrew (100)", value: "he" },
  { label: "Punjabi (95)", value: "pa" },
  { label: "Urdu (24)", value: "ur" },
];

export const sortOptions = [
  { label: "Sort By: Latest", value: "latest" },
  { label: "Oldest", value: "oldest" },
  { label: "Featured", value: "featured" },
  { label: "Seeds", value: "seeds" },
  { label: "Peers", value: "peers" },
  { label: "Year", value: "year" },
  { label: "IMDb Rating", value: "rating" },
  { label: "YTS Likes", value: "likes" },
  { label: "RT Audience", value: "rt_audience" },
  { label: "Alphabetical", value: "alphabetical" },
  { label: "Downloads", value: "downloads" },
];